services:
  devmentor:
    build: .
    image: devmentor
    stdin_open: true
    tty: true
    env_file:
      - .env
    
    environment:
      - VECTOR_STORE_PATH=/app/vector_store
    
    volumes:
      - ../vector_store:/app/vector_store