services:
  # Service 1: The Streamlit Web App (this is the default)
  app:
    build: .
    image: devmentor
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - VECTOR_STORE_PATH=/app/vector_store
    volumes:
      - ../vector_store:/app/vector_store

  # Service 2: The Command-Line Interface (CLI)
  cli:
    build: .
    image: devmentor
    stdin_open: true  # Required for the interactive CLI
    tty: true         # Required for the interactive CLI
    env_file:
      - .env
    environment:
      - VECTOR_STORE_PATH=/app/vector_store
    volumes:
      - ../vector_store:/app/vector_store
    # override the Dockerfile's CMD
    command: ["python", "query_rag.py"]