name: DevMentor CI

# Define the events that will trigger this workflow.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs to be executed.
jobs:
  # Define a single job with the ID 'build-cpu'.
  build-cpu:
    # Specify that this job will run on a standard Ubuntu runner.
    runs-on: ubuntu-latest

    # Define the sequence of steps for this job.
    steps:
      # Step 1: Download the repository's code onto the runner.
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Step 2: Build the CPU-specific Docker image.
      - name: Build Docker image (CPU)
        run: docker compose build app-cpu